# Site settings
title: Vigor's Blog 
email: 
description: > # this means to ignore newlines until "baseurl:"
 Chasing...
baseurl: "/arctic-fox-theme" # the subpath of your site, e.g. /blog/
url: "http://vigor95.github.io" # the base hostname & protocol for your site
twitter_username: username
github_username: vigor95

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
